services:
  web:
    build: .
    ports:
      - "${FLASK_RUN_PORT}:${FLASK_RUN_PORT}"
    environment:
      - FLASK_ENV=production
      - FLASK_RUN_HOST=0.0.0.0
      - FLASK_RUN_WORKERS=5
      - FLASK_RUN_TIMEOUT=60
    env_file:
      - ./.env
    volumes:
      - ${SSL_CERT_PATH}:/etc/ssl/certs/fullchain.pem:ro
      - ${SSL_KEY_PATH}:/etc/ssl/private/privkey.pem:ro
      - .:/app
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "1"
    depends_on:
      - database

  database:
    image: mariadb:10.5.19
    ports:
      - "3307:3306"
    env_file:
      - ./db/.env
    volumes:
      - db-data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "1"

  worker:
    build: .
    command: celery -A make_celery.celery worker --loglevel=info -Q priority,default
    volumes:
      - .:/app
    depends_on:
      - redis
      - web
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "1"

  beat:
    build: .
    command: celery -A make_celery.celery beat --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - redis
      - web
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "1"

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    depends_on:
      - web
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "1"
    volumes:
      - redis-data:/data

volumes:
  db-data:
  redis-data: