# Utilizar la imagen base que hemos construido
FROM booking-base

# Instalar Apache y mod_wsgi
RUN apt-get update && apt-get install -y \
    apache2 \
    libapache2-mod-wsgi-py3 \
    && rm -rf /var/lib/apt/lists/*

# Hacer que el script de entrada sea ejecutable
COPY docker/docker-entrypoint.sh /usr/local/bin/docker-entrypoint.sh
# Convertir formato de línea de CRLF a LF y dar permisos
RUN sed -i 's/\r$//' /usr/local/bin/docker-entrypoint.sh && \
    chmod +x /usr/local/bin/docker-entrypoint.sh
# Exponer el puerto para el tráfico web
EXPOSE ${PORT:-443}

# Usar el entrypoint para iniciar Apache y Flask
ENTRYPOINT ["/usr/local/bin/docker-entrypoint.sh"]