version: '3'
services:
  web:
    build:
      context: ../
      dockerfile: daniieelgs/booking-flask:latest
    env_file:
      - ../.env
    environment:
      - FLASK_ENV=production
      - FLASK_DEBUG=0
      - TZ=Europe/Madrid
      - PORT=${PORT:-443}
      - SSL_CERT_FILE=${SSL_CERT_FILE}
      - SSL_KEY_FILE=${SSL_KEY_FILE}
    volumes:
      - ${SSL_CERT_FILE_HOST}:${SSL_CERT_FILE}:ro
      - ${SSL_KEY_FILE_HOST}:${SSL_KEY_FILE}:ro
      - ..:/app
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - database
    restart: always

  database:
    image: mariadb:10.5.19
    ports:
      - "3307:3306"
    environment:
      - TZ=Europe/Madrid
    env_file:
      - ../db/.env
    volumes:
      - db-data:/var/lib/mysql
      - ../db/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always

  worker:
    build:
      context: ../
      dockerfile: daniieelgs/booking-base:latest
    command: celery -A make_celery.celery worker --loglevel=info -Q priority,default
    volumes:
      - ..:/app
    depends_on:
      - redis
      - database
    restart: always

  beat:
    build:
      context: ../
      dockerfile: daniieelgs/booking-base:latest
    command: celery -A make_celery.celery beat --loglevel=info
    volumes:
      - ..:/app
    depends_on:
      - redis
      - database
    restart: always

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    environment:
      - TZ=Europe/Madrid
    restart: always
    volumes:
      - redis-data:/data

volumes:
  db-data:
  redis-data: