version: '3'
services:
  web:
    image: booking-flask
    environment:
      - FLASK_ENV=${FLASK_ENV:-production}
      - FLASK_DEBUG=${FLASK_DEBUG:-0}
      - TZ=Europe/Madrid
      - PORT=${PORT:-443}
      - SSL_CERT_FILE=${SSL_CERT_PATH}
      - SSL_KEY_FILE=${SSL_KEY_PATH}
      - SERVER_NAME=${SERVER_NAME}
      - APACHE_LOG_DIR=/var/log/apache2
    volumes:
      - ${SSL_CERT_PATH}:/etc/ssl/certs/fullchain.pem:ro
      - ${SSL_KEY_PATH}:/etc/ssl/private/privkey.pem:ro
      - ..:/app
    ports:
      - "${PORT:-443}:${PORT:-443}"
    depends_on:
      - database
    restart: always

  database:
    image: mariadb:10.5.19
    ports:
      - "${DB_PORT:-3307}:3306"
    environment:
      - TZ=Europe/Madrid
    env_file:
      - ../db/.env
    volumes:
      - db-data:/var/lib/mysql
      - ../db/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always

  worker:
    image: booking-base
    command: celery -A make_celery.celery worker --loglevel=info -Q priority,default
    volumes:
      - ..:/app
    depends_on:
      - redis
      - database
    restart: always

  beat:
    image: booking-base
    command: celery -A make_celery.celery beat --loglevel=info
    volumes:
      - ..:/app
    depends_on:
      - redis
      - database
    restart: always

  redis:
    image: redis:alpine
    ports:
      - "${REDIS_PORT:-6379}:6379"
    environment:
      - TZ=Europe/Madrid
    restart: always
    volumes:
      - redis-data:/data

volumes:
  db-data:
  redis-data: