# Utilizar la imagen base que hemos construido
FROM daniieelgs/booking-base

# Instalar Apache y mod_wsgi
RUN apt-get update && apt-get install -y \
    apache2 \
    libapache2-mod-wsgi-py3 \
    && rm -rf /var/lib/apt/lists/*

# Hacer que el script de entrada sea ejecutable
RUN chmod +x /docker/docker-entrypoint.sh

# Exponer el puerto para el tráfico web
EXPOSE ${PORT:-443}

# Usar el entrypoint para iniciar Apache y Flask
ENTRYPOINT ["/docker/docker-entrypoint.sh"]
